sudo: required

services:
- docker

jobs:
  include:
  - stage: "Tests"
    name: "core-test"
    script:
    - make build
    - make test
  - script:
    - make build
    - make test_source_target
    name: "source-target-test"